import { describe, expect, it } from 'vitest';
import { ShapeGeometry } from 'three';
import { siteFrame, type SiteBoundary } from './geography';
import { footprintShape, roadVertices } from './environment';

const boundary: SiteBoundary = { type: 'Polygon', coordinates: [
  [[106.695, 10.770], [106.705, 10.770], [106.705, 10.779], [106.695, 10.779], [106.695, 10.770]],
] };

describe('WGS84 → ECEF → ENU → Three metre frame', () => {
  it('derives a deterministic bounding-extent origin independent of vertex order and holes', () => {
    const frame = siteFrame(boundary);
    expect(frame.origin).toEqual([expect.closeTo(106.7, 12), expect.closeTo(10.7745, 12)]);
    expect(siteFrame({ ...boundary, coordinates: [[...boundary.coordinates[0]].reverse()] }).origin).toEqual(frame.origin);
    frame.toScene(frame.origin).forEach((value) => expect(value === 0).toBe(true));
    frame.toGround(frame.origin).forEach((value) => expect(value === 0).toBe(true));
  });

  // Independent EPSG:4979 → EPSG:4978 fixtures generated by PostGIS ST_Transform (PROJ),
  // rotated into the stated frame by SQL. Absolute tolerance: 1 mm per axis at ~7.8 km.
  it.each([
    [[106.70001, 10.7745], [1.093697838961, -0.000000093173, -0.000000017731]],
    [[106.7, 10.77451], [-0.000000000035, -0.000000097188, -1.106130914604]],
    [[106.697, 10.777], [-328.106644451259, -0.014471387094, -276.534356553085]],
    [[106.75, 10.8245], [5467.584162824533, -4.756833837060, -5531.108774624941]],
  ])('matches independent reference %j within 1 mm', (geographic, reference) => {
    const actual = siteFrame(boundary).toScene(geographic);
    actual.forEach((coordinate, index) => expect(Math.abs(coordinate - reference[index])).toBeLessThan(0.001));
  });

  it('preserves east/west and north/south signs and metre scale', () => {
    const { toGround } = siteFrame(boundary);
    expect(toGround([106.70001, 10.7745])[0]).toBeCloseTo(1.09369784, 6);
    expect(toGround([106.69999, 10.7745])[0]).toBeLessThan(0);
    expect(toGround([106.7, 10.77451])[2]).toBeCloseTo(-1.10613091, 6);
    expect(toGround([106.7, 10.77449])[2]).toBeGreaterThan(0);
    expect(toGround([106.75, 10.8245])[1]).toBe(0);
  });

  it('derives framing from boundary without rescaling geography', () => {
    const frame = siteFrame(boundary);
    expect(frame.radius).toBeGreaterThan(700);
    expect(frame.radius).toBeLessThan(750);
    for (const [x, , z] of frame.rings[0]) {
      expect(Math.hypot(x - frame.center[0], z - frame.center[2])).toBeLessThanOrEqual(frame.radius);
    }
    const smaller = siteFrame({ type: 'Polygon', coordinates: [[[106.699, 10.774], [106.701, 10.774],
      [106.701, 10.775], [106.699, 10.775], [106.699, 10.774]]] });
    expect(smaller.radius).toBeLessThan(frame.radius / 4);
  });

  it('converts every Polygon interior ring and removes holes from triangulated ground', () => {
    const hole = [[106.699, 10.774], [106.701, 10.774], [106.701, 10.775], [106.699, 10.775], [106.699, 10.774]];
    const frame = siteFrame({ ...boundary, coordinates: [...boundary.coordinates, hole] });
    expect(frame.origin).toEqual(siteFrame(boundary).origin);
    expect(frame.rings[1]).toEqual(hole.map(frame.toGround));
    const shape = footprintShape(frame.rings);
    expect(shape.holes).toHaveLength(1);
    const geometry = new ShapeGeometry(shape);
    const positions = geometry.getAttribute('position');
    const indices = geometry.index!;
    let area = 0;
    for (let index = 0; index < indices.count; index += 3) {
      const a = indices.getX(index), b = indices.getX(index + 1), c = indices.getX(index + 2);
      area += Math.abs((positions.getX(b) - positions.getX(a)) * (positions.getY(c) - positions.getY(a))
        - (positions.getY(b) - positions.getY(a)) * (positions.getX(c) - positions.getX(a))) / 2;
    }
    expect(area).toBeGreaterThan(1_000_000);
    expect(area).toBeLessThan(1_080_000);
    geometry.dispose();
  });

  it('uses metre widths on converted road centerlines without moving their centers', () => {
    const vertices = roadVertices([[0, 0, 0], [100, 0, 0]], 10);
    expect([...vertices.slice(0, 3)]).toEqual([0, expect.closeTo(0.3), 5]);
    expect([...vertices.slice(6, 9)]).toEqual([0, expect.closeTo(0.3), -5]);
  });
});
